import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,ease=t=>t*t*(3-2*t);
function rng(seed=1){let a=seed>>>0;return()=>{a|=0;a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296}}const R=rng(17092027);
const host=document.getElementById('city');
const scene=new THREE.Scene();scene.background=new THREE.Color(0xa9afaa);scene.fog=new THREE.Fog(0xa7ada8,28,330);
const camera=new THREE.PerspectiveCamera(59,innerWidth/innerHeight,.05,1500);
const renderer=new THREE.WebGLRenderer({antialias:innerWidth>900,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<768?1.0:1.4));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.94;host.appendChild(renderer.domElement);
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();window.dispatchEvent(new Event('atlas-city-lost'))},{passive:false});
scene.add(new THREE.HemisphereLight(0xd1d6d1,0x484d49,1.25));const sun=new THREE.DirectionalLight(0xeee8dc,1.65);sun.position.set(7,10,4);scene.add(sun);const fill=new THREE.DirectionalLight(0xa9b2ac,.36);fill.position.set(-7,4,-2);scene.add(fill);

function concreteTexture(seed=1){const rr=rng(seed),n=256,c=document.createElement('canvas');c.width=c.height=n;const x=c.getContext('2d');x.fillStyle='#83847e';x.fillRect(0,0,n,n);const img=x.getImageData(0,0,n,n),d=img.data;for(let i=0;i<d.length;i+=4){const v=(rr()-.5)*26;d[i]=clamp(d[i]+v,0,255);d[i+1]=clamp(d[i+1]+v*.92,0,255);d[i+2]=clamp(d[i+2]+v*.80,0,255)}x.putImageData(img,0,0);x.globalAlpha=.16;x.strokeStyle='#41443f';x.lineWidth=1;for(let i=0;i<25;i++){let px=rr()*n,py=rr()*n;x.beginPath();x.moveTo(px,py);for(let j=0;j<3+Math.floor(rr()*5);j++){px+=(rr()-.5)*30;py+=(rr()-.5)*30;x.lineTo(px,py)}x.stroke()}x.globalAlpha=.12;x.fillStyle='#c2c0b7';for(let i=0;i<40;i++){const px=rr()*n,py=rr()*n,s=2+rr()*10;x.fillRect(px,py,s,s*.35)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(2,2);return t}
const texA=concreteTexture(171),texB=concreteTexture(172),texC=concreteTexture(173);
const concrete=new THREE.MeshStandardMaterial({map:texA,color:0x96948d,roughness:1});const concreteDark=new THREE.MeshStandardMaterial({map:texB,color:0x696b66,roughness:1});const concreteLight=new THREE.MeshStandardMaterial({map:texC,color:0xaaa79f,roughness:1});const facade=new THREE.MeshStandardMaterial({map:texB,color:0x85847d,roughness:1});const voidMat=new THREE.MeshStandardMaterial({color:0x303431,roughness:1});const roadMat=new THREE.MeshStandardMaterial({color:0x4b504c,roughness:1});const groundMat=new THREE.MeshStandardMaterial({color:0x5c615c,roughness:1});const rubbleMat=new THREE.MeshStandardMaterial({map:texB,color:0x76766f,roughness:1});const slabMat=new THREE.MeshStandardMaterial({map:texC,color:0x97948b,roughness:1});const rebarMat=new THREE.MeshStandardMaterial({color:0x2d302e,roughness:.9});

function skyTexture(){const w=1024,h=320,c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,'#8e9995');g.addColorStop(.48,'#aeb5b0');g.addColorStop(1,'#c6c9c2');x.fillStyle=g;x.fillRect(0,0,w,h);for(let i=0;i<90;i++){const px=R()*w,py=R()*h*.78,rx=45+R()*150,ry=18+R()*54,rg=x.createRadialGradient(px,py,0,px,py,rx),s=110+Math.floor(R()*60);rg.addColorStop(0,`rgba(${s},${s+6},${s+4},${.10+R()*.16})`);rg.addColorStop(.58,`rgba(${s+18},${s+20},${s+18},${.035+R()*.08})`);rg.addColorStop(1,'rgba(255,255,255,0)');x.save();x.translate(px,py);x.scale(1,ry/rx);x.translate(-px,-py);x.fillStyle=rg;x.fillRect(px-rx,py-rx,rx*2,rx*2);x.restore()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
const sky=new THREE.Mesh(new THREE.PlaneGeometry(1100,340),new THREE.MeshBasicMaterial({map:skyTexture(),depthWrite:false,fog:false}));sky.position.set(0,94,-670);scene.add(sky);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(760,1120),groundMat);ground.rotation.x=-Math.PI/2;ground.position.set(0,-.22,-260);scene.add(ground);

const route=new THREE.CatmullRomCurve3([
 new THREE.Vector3(24,0,70),new THREE.Vector3(15,0,20),new THREE.Vector3(-18,0,-72),new THREE.Vector3(-10,0,-150),new THREE.Vector3(22,0,-238),new THREE.Vector3(15,0,-320),new THREE.Vector3(-13,0,-412),new THREE.Vector3(0,0,-510)
],false,'catmullrom',.42);
function routeFrame(q){q=clamp(q);const p=route.getPoint(q),t=route.getTangent(q).normalize(),n=new THREE.Vector3(-t.z,0,t.x).normalize();return{p,t,n}}
const box=new THREE.BoxGeometry(1,1,1),roadParts=[];const M=new THREE.Matrix4(),P=new THREE.Vector3(),Q=new THREE.Quaternion(),S=new THREE.Vector3();
for(let i=0;i<72;i++){const a=route.getPoint(i/72),b=route.getPoint((i+1)/72),m=a.clone().add(b).multiplyScalar(.5),dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz),ang=Math.atan2(dx,dz);P.set(m.x,.01,m.z);Q.setFromEuler(new THREE.Euler(0,ang,0));S.set(15,.055,len+1.0);M.compose(P,Q,S);roadParts.push(M.clone())}
const road=new THREE.InstancedMesh(box,roadMat,roadParts.length);roadParts.forEach((m,i)=>road.setMatrixAt(i,m));road.instanceMatrix.needsUpdate=true;scene.add(road);

const buckets=[[],[],[],[],[]];
function push(bucket,x,y,z,sx,sy,sz,rx=0,ry=0,rz=0){P.set(x,y,z);Q.setFromEuler(new THREE.Euler(rx,ry,rz));S.set(sx,sy,sz);M.compose(P,Q,S);buckets[bucket].push(M.clone())}
function pushLocal(base,bucket,x,y,z,sx,sy,sz,rx=0,ry=0,rz=0){P.set(x,y,z);Q.setFromEuler(new THREE.Euler(rx,ry,rz));S.set(sx,sy,sz);const lm=new THREE.Matrix4().compose(P,Q,S);buckets[bucket].push(base.clone().multiply(lm))}

function ruinedBuilding(q,side,offset,w,d,floors,damage=.62,hero=false){const rf=routeFrame(q),pos=rf.p.clone().add(rf.n.clone().multiplyScalar(side*offset)),ang=Math.atan2(rf.t.x,rf.t.z)+(side<0?Math.PI:0),base=new THREE.Matrix4().makeRotationY(ang);base.setPosition(pos.x,0,pos.z);const fh=4.05,coreH=floors*fh*(.58+R()*.28),coreW=w*(.40+R()*.18),coreD=d*(.45+R()*.18);pushLocal(base,R()>.5?0:3,0,coreH/2,0,coreW,coreH,coreD);
 for(let f=0;f<floors;f++){const y=f*fh,top=f/Math.max(1,floors-1),ld=damage*(.72+.48*top),missing=R()<ld*(top>.55?.34:.11);if(!missing){const cut=R()<ld*.58,shift=cut?(R()>.5?1:-1)*w*.13:0;pushLocal(base,2,shift,y+.02,(R()-.5)*d*.08,w*(cut?.62+R()*.20:.92),.22,d*(.73+R()*.20),0,0,(R()-.5)*.06)}else if(R()>.38){pushLocal(base,0,(R()-.5)*w*.32,y+.02,(R()-.5)*d*.30,w*(.18+R()*.30),.18,d*(.18+R()*.34),0,(R()-.5)*.10,(R()-.5)*.24)}
  const bays=Math.max(3,Math.round(w/4.8));for(let b=0;b<bays;b++){const bx=-w/2+(b+.5)*w/bays,keep=R()>ld*(hero?.32:.44);if(keep){if(hero&&R()>.28){const bw=w/bays*.78,bh=fh*.66,strip=Math.max(.18,bw*.13);pushLocal(base,3,bx-bw*.5+strip*.5,y+fh*.52,-d/2-.08,strip,bh,.20);pushLocal(base,3,bx+bw*.5-strip*.5,y+fh*.52,-d/2-.08,strip,bh,.20);pushLocal(base,3,bx,y+fh*.52+bh*.5-strip*.45,-d/2-.08,bw,strip*.9,.20);pushLocal(base,3,bx,y+fh*.52-bh*.5+strip*.45,-d/2-.08,bw,strip*.9,.20);pushLocal(base,4,bx,y+fh*.52,-d/2+.06,bw*.68,bh*.60,.12)}else{pushLocal(base,3,bx,y+fh*.52,-d/2-.08,w/bays*.76,fh*(.64+R()*.16),.20)}}else if(R()>.45){pushLocal(base,4,bx,y+fh*.52,-d/2+.10,w/bays*.62,fh*.50,.12)}}
  if(R()>ld*.38)pushLocal(base,3,-w/2-.06,y+fh*.52,(R()-.5)*d*.16,.20,fh*(.62+R()*.18),d*(.50+R()*.33));if(R()>ld*.50)pushLocal(base,0,w/2+.06,y+fh*.52,(R()-.5)*d*.18,.20,fh*(.58+R()*.20),d*(.42+R()*.38));if(R()<ld*.82){const cols=Math.max(2,Math.round(w/6));for(let c=0;c<=cols;c++)if(R()>.38)pushLocal(base,1,-w/2+c*w/cols,y+fh*.5,-d/2,.30,fh,.30)}}
 const hang=hero?4+Math.floor(R()*4):1+Math.floor(R()*3);for(let i=0;i<hang;i++)pushLocal(base,R()>.55?0:1,(R()-.5)*w*.42,(floors*(.48+R()*.46))*fh,(R()-.5)*d*.42,w*(.18+R()*.34),.16,d*(.16+R()*.38),(R()-.5)*.28,(R()-.5)*.16,(R()-.5)*.34);
 if(R()<damage*.95)pushLocal(base,2,(R()-.5)*w*.48,1.0+R()*2.0,(R()-.5)*d*.55,w*(.32+R()*.38),.16,d*(.22+R()*.36),(R()-.5)*.9,(R()-.5)*.4,(R()-.5)*.7)
}

const heroQs=[.04,.11,.18,.26,.34,.43,.52,.61,.70,.79,.88,.96];heroQs.forEach((q,i)=>{const side=i%2?1:-1;ruinedBuilding(q,side,23+R()*8,24+R()*10,18+R()*7,8+Math.floor(R()*7),.56+R()*.16,true);ruinedBuilding(clamp(q+.025),-side,31+R()*10,18+R()*8,15+R()*6,6+Math.floor(R()*6),.50+R()*.20,false)});
for(let i=0;i<46;i++){const q=.015+R()*.97,side=R()>.5?1:-1;ruinedBuilding(q,side,28+R()*50,14+R()*18,12+R()*15,5+Math.floor(R()*8),.42+R()*.28,false)}
for(let b=0;b<5;b++){const arr=buckets[b],inst=new THREE.InstancedMesh(box,[concrete,concreteDark,concreteLight,facade,voidMat][b],arr.length);arr.forEach((m,i)=>inst.setMatrixAt(i,m));inst.instanceMatrix.needsUpdate=true;inst.frustumCulled=false;scene.add(inst)}

const slabCount=760,slabs=new THREE.InstancedMesh(box,slabMat,slabCount);for(let i=0;i<slabCount;i++){const q=R(),rf=routeFrame(q),side=R()>.5?1:-1,center=R()<.12,off=center?(R()-.5)*9:side*(10+R()*58),pos=rf.p.clone().add(rf.n.clone().multiplyScalar(off)),ss=center?.45+R()*1.25:.9+R()*4.2;P.set(pos.x,.16+R()*.9,pos.z);Q.setFromEuler(new THREE.Euler((R()-.5)*.68,Math.atan2(rf.t.x,rf.t.z)+R()*Math.PI,(R()-.5)*.75));S.set(ss*(.8+R()*1.6),.11+R()*.28,ss*(.45+R()*1.4));M.compose(P,Q,S);slabs.setMatrixAt(i,M)}slabs.instanceMatrix.needsUpdate=true;scene.add(slabs);
const rubbleCount=1150,rubble=new THREE.InstancedMesh(new THREE.TetrahedronGeometry(1,0),rubbleMat,rubbleCount);for(let i=0;i<rubbleCount;i++){const q=R(),rf=routeFrame(q),rr=.18+R()*1.45,side=R()>.5?1:-1,off=(rr>.72?side*(12+R()*62):(R()-.5)*105),pos=rf.p.clone().add(rf.n.clone().multiplyScalar(off));P.set(pos.x,.10+R()*.58,pos.z);Q.setFromEuler(new THREE.Euler(R()*Math.PI,R()*Math.PI,R()*Math.PI));S.set(rr*(.4+R()*1.4),rr*(.20+R()*.60),rr*(.5+R()*1.7));M.compose(P,Q,S);rubble.setMatrixAt(i,M)}rubble.instanceMatrix.needsUpdate=true;scene.add(rubble);
const rebarCount=340,rebars=new THREE.InstancedMesh(box,rebarMat,rebarCount);for(let i=0;i<rebarCount;i++){const q=R(),rf=routeFrame(q),side=R()>.5?1:-1,off=side*(12+R()*70),pos=rf.p.clone().add(rf.n.clone().multiplyScalar(off)),len=1.8+R()*5.4;P.set(pos.x,.22+R()*1.2,pos.z);Q.setFromEuler(new THREE.Euler((R()-.5)*.8,R()*Math.PI,(R()-.5)*.8));S.set(.045+R()*.05,.045+R()*.05,len);M.compose(P,Q,S);rebars.setMatrixAt(i,M)}rebars.instanceMatrix.needsUpdate=true;scene.add(rebars);

function smokeTexture(){const n=128,c=document.createElement('canvas');c.width=c.height=n;const x=c.getContext('2d');for(let i=0;i<7;i++){const px=n*(.34+R()*.32),py=n*(.34+R()*.30),r=n*(.18+R()*.27),g=x.createRadialGradient(px,py,0,px,py,r);g.addColorStop(0,'rgba(88,96,91,.25)');g.addColorStop(.55,'rgba(76,85,80,.11)');g.addColorStop(1,'rgba(68,76,72,0)');x.fillStyle=g;x.beginPath();x.arc(px,py,r,0,Math.PI*2);x.fill()}return new THREE.CanvasTexture(c)}const smokeTex=smokeTexture();for(let i=0;i<8;i++){const q=.10+i*.115,rf=routeFrame(q),side=i%2?1:-1,basePos=rf.p.clone().add(rf.n.clone().multiplyScalar(side*(25+R()*30)));for(let j=0;j<4;j++){const sm=new THREE.Sprite(new THREE.SpriteMaterial({map:smokeTex,color:0x949b95,transparent:true,opacity:.17,depthWrite:false}));sm.position.set(basePos.x+(R()-.5)*7,8+j*7+R()*4,basePos.z+(R()-.5)*7);const ss=18+j*8+R()*9;sm.scale.set(ss,ss*.9,1);scene.add(sm)}}

let camPos=new THREE.Vector3(),look=new THREE.Vector3(),camReady=false,last=performance.now(),readySent=false;
function draw(now){requestAnimationFrame(draw);const dt=Math.min((now-last)/1000,.05);last=now;const max=document.documentElement.scrollHeight-innerHeight,pct=max>0?scrollY/max:0,t=pct*10.005;let cp=clamp((t-4.82)/(10.005-4.82));cp=cp*(.76+.24*cp);const rf=routeFrame(cp),ahead=routeFrame(clamp(cp+.065)),y=lerp(34,15.8,ease(cp)),ly=lerp(12,7,ease(cp)),targetPos=new THREE.Vector3(rf.p.x,y,rf.p.z),targetLook=new THREE.Vector3(ahead.p.x,ly,ahead.p.z);if(!camReady){camPos.copy(targetPos);look.copy(targetLook);camReady=true}else{camPos.lerp(targetPos,1-Math.exp(-18*dt));look.lerp(targetLook,1-Math.exp(-15*dt))}camera.position.copy(camPos);camera.lookAt(look);camera.fov=lerp(59,67.5,ease(cp));camera.updateProjectionMatrix();scene.fog.near=lerp(30,18,cp);scene.fog.far=lerp(335,225,cp);scene.fog.color.set(0xa9afaa).lerp(new THREE.Color(0x979f9a),cp*.34);renderer.toneMappingExposure=lerp(.95,.90,cp);sky.position.x=camera.position.x*.18;renderer.render(scene,camera);if(!readySent){readySent=true;window.dispatchEvent(new Event('atlas-city-ready'))}}
requestAnimationFrame(draw);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<768?1.0:1.4))});